
version: '3.8'

services:
  mavhir:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAVHIR_ENVIRONMENT=production
      - MAVHIR_DEBUG=false
      - MAVHIR_LOG_LEVEL=INFO
      - MAVHIR_REDIS_URL=redis://redis:6379/0
    volumes:
      - ./models:/app/models:ro
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Database
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: mavhir
  #     POSTGRES_USER: mavhir
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  redis_data:
  # postgres_data:

networks:
  default:
    name: mavhir_network
